spring:
  application:
    name: SERVICE-REGISTRY
  cloud:
    config:
      enabled: false
#  config:
#    import: optional:configserver:http://localhost:9296
#  cloud:
#    config:
#      enabled: true
#      uri: http://localhost:9296

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false