spring:
  application:
    name: API-GATEWAY
  config:
    import: optional:configserver:http://localhost:9296
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: USER-SERVICE
              uri: lb://USER-SERVICE
              predicates:
                - Path=/users/**
              filters:
                - name: CircuitBreaker
                  args:
                    id: userServiceCircuit
                    fallbackUri: forward:/userServiceFallBack

            - id: DEPARTMENT-SERVICE
              uri: lb://DEPARTMENT-SERVICE
              predicates:
                - Path=/departments/**
              filters:
                - name: CircuitBreaker
                  args:
                    id: departmentServiceCircuit
                    fallbackUri: forward:/departmentServiceFallBack

resilience4j:
  circuitbreaker:
    instances:
      userServiceCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      departmentServiceCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  timelimiter:
    instances:
      userServiceCircuitBreaker:
        timeoutDuration: 4s
      departmentServiceCircuitBreaker:
        timeoutDuration: 4s

server:
  port: 9191
