spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: USER-SERVICE
              uri: lb://USER-SERVICE
              predicates:
                - Path=/users/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: USER-SERVICE
                    fallbackUri: forward:/userServiceFallBack
            - id: DEPARTMENT-SERVICE
              uri: lb://DEPARTMENT-SERVICE
              predicates:
                - Path=/departments/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: DEPARTMENT-SERVICE
                    fallbackUri: forward:/departmentServiceFallBack

resilience4j:
  circuitbreaker:
    instances:
      userServiceCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  timelimiter:
    instances:
      userServiceCircuitBreaker:
        timeoutDuration: 4s


#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream
server:
  port: 9191
