spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: USER-SERVICE
              uri: lb://USER-SERVICE
              predicates:
                - Path=/users/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: USER-SERVICE
                    fallbackUri: forward:/userServiceFallBack
            - id: DEPARTMENT-SERVICE
              uri: lb://DEPARTMENT-SERVICE
              predicates:
                - Path=/departments/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: DEPARTMENT-SERVICE
                    fallbackUri: forward:/departmentServiceFallBack

hystrix:
  command:
    fallbackCmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

server:
  port: 9191

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost